title: "Mehrdad Mohammadi"
author: "Mehrdad Mohammadi"
description: "University of Illinois at Urbana-Champaign"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
mathjax: true

# Layout
show_social: true          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu
navigation:
  - {title: "Home", url: "mehrdadmhmdi.github.io", icon: home}
  - {title: "News", file: "news.md"}
  - {title: "CV", file: "CV.md"}
  - {title: "Research", file: "research.md"}
  - {title: "Software", file: "softwares.md"}
  - {title: "Contact", file: "contact.md"}


# External links (icons)
external:
  - {title: Mail, icon: envelope, url: "mailto:mehrdad3@illinois.edu"}
  - {title: google-scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=ALnHM1oAAAAJ&hl=en"}
  - {title: Github, icon: github, url: "https://github.com/mehrdadmhmdi"}
  - {title: X, icon: x-twitter, url: "https://twitter.com/mehrdad_mhmd"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/mehrdadmohammadi/"}

# Comments (optional)
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-category-pages
  - jekyll-tagging
  - jekyll-scholar

scholar:
  source: ./_bibliography
  bibliography: publications.bib
  style: apa
  locale: en
  sort_by: year
  order: descending
  bibliography_template: bib

